# Generated by Django 4.2.2 on 2023-06-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_service_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
